# Generated by Django 4.0.3 on 2022-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(max_length=150)),
                ('detail_type', models.CharField(choices=[('inner', 'inner'), ('engine', 'engine'), ('vehicle', 'vehicle')], max_length=20)),
            ],
        ),
    ]
