# Generated by Django 4.0.3 on 2022-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardetail',
            options={'verbose_name': 'Car Detail', 'verbose_name_plural': 'Car Details'},
        ),
        migrations.AddField(
            model_name='cardetail',
            name='brand',
            field=models.CharField(choices=[('Mercedes', 'Mercedes'), ('BMV', 'BMV'), ('Chevrolet', 'Chevrolet'), ('Volkswagen', 'Volkswagen'), ('Opel', 'Opel'), ('Mitsubishi', 'Mitsubishi')], default=None, max_length=60),
            preserve_default=False,
        ),
    ]
