# Generated by Django 4.0.3 on 2022-03-03 14:08

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cardetail_options_cardetail_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='photo',
            field=models.ImageField(default=None, upload_to=home.models.detail_image_upload),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='brand',
            field=models.CharField(choices=[('Mercedes', 'Mercedes'), ('BMV', 'BMV'), ('Chevrolet', 'Chevrolet'), ('Volkswagen', 'Volkswagen'), ('Opel', 'Opel'), ('Mitsubishi', 'Mitsubishi'), ('Audi', 'Audi')], max_length=60),
        ),
    ]
