# Generated by Django 4.0.3 on 2022-03-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cardetail_count_alter_cardetail_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='brand',
            field=models.CharField(choices=[('Mercedes', 'Mercedes'), ('BMV', 'BMV'), ('Chevrolet', 'Chevrolet'), ('Volkswagen', 'Volkswagen'), ('Opel', 'Opel'), ('Mitsubishi', 'Mitsubishi'), ('Audi', 'Audi'), ('Nissan', 'Nissan'), ('Infiniti', 'Infiniti'), ('Kia', 'Kia'), ('Hyundai', 'Hyundai'), ('Suzuki', 'Suzuki'), ('Lexus', 'Lexus'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Toyota', 'Toyota')], max_length=60),
        ),
    ]
