# Generated by Django 4.0.3 on 2022-09-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_carbrand_created_carbrand_modified_cardetail_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Бренд машины', 'verbose_name_plural': 'Бренды машин'},
        ),
        migrations.AlterModelOptions(
            name='cardetail',
            options={'verbose_name': 'Детали машыны', 'verbose_name_plural': 'Детали машын'},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Машыны'},
        ),
        migrations.CreateModel(
            name='PhotosServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_general', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.service')),
            ],
            options={
                'verbose_name': 'фото для Сервиса',
                'verbose_name_plural': 'фото для Сервис',
            },
        ),
    ]
