# Generated by Django 4.0.3 on 2022-09-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_carphotolist_alter_cars_photo_delete_photosservices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carphotolist',
            options={'verbose_name': 'фото для Автомобилья', 'verbose_name_plural': 'фото для Машыны'},
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(default='Black', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.CharField(default='Gasoline', max_length=155),
        ),
        migrations.AddField(
            model_name='cars',
            name='hand_drive',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=10),
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(default=125000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT')], default='Automatic', max_length=155),
        ),
    ]
